# Generated by Django 2.2 on 2019-05-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='statusid',
            new_name='status',
        ),
    ]
